server:
  port: 7070




spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hectorpq/ms_catalogo.git # ruta del repositorio git
          searchPaths: config-data
          default-label: main
